# To run these tests, use the REST Client VS Code plugin.
# More info here: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

POST http://localhost:5000/login/signup
Content-Type: application/json

{
    "email": "mike@hems.com",
    "password": "PW123"
}

###

# Should be able to log in with user just created
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "mike@hems.com",
    "password": "PW1234"
}

###

# Bad password
POST http://localhost:5000/login
content-type: application/json

{
    "email": "mike@hems.com",
    "password": "BadPW"
}


###
# Should fail if no token is included
POST http://localhost:5000/login/logout

###
POST http://localhost:5000/login/logout
Authorization: Bearer f4ebdfd8-ca5c-44d7-9667-efa837dc9284

###
POST http://localhost:5000/login/password
content-type: application/json
Authorization: Bearer 161ce6a9-92a1-4731-a844-d9c2a94b6dfc

{
    "password": "PW1234"
}